[tools]
terraform = "latest"
python = "3"
opentofu = "latest"

[settings]
legacy_version_file = false

[env]
# TF_CLI_ARGS = "-var-file=../variables.tf"

# AWS credentials may be added like so:
# [env]
# AWS_REGION =
# AWS_ACCESS_KEY_ID =
# AWS_SECRET_ACCESS_KEY =
